apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontend
  name: payment-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment-con
        image: node:12-alpine
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment
  ports:
  - port: 50052
    targetPort: 50051
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
